name: Bygg Windows EXE

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pygame pyinstaller
      - run: pyinstaller --onefile --noconsole haxbrygden.py
      - uses: actions/upload-artifact@v3
        with:
          name: haxbrygden-windows
          path: dist/haxbrygden.exe
